### ISSUE TITLE
On dependencies: tui or cursive?

### ISSUE THREAD

**Issue by saona-raimundo** [DioxusLabs/rink#2]
First of all, thank you very much for the whole dioxus initiative!

I was planning to enhance the ecosystem around [sycamore](https://crates.io/crates/sycamore) with a TUI renderer that would handle a subset of html... just as this project! And well, as a TUI that renders some Html can be an independent project (of sycamore or dioxus), I wanted to ask: looking at the dependencies, what made you decide to use [tui](https://crates.io/crates/tui/) instead of [cursive](https://crates.io/crates/cursive)?

Here is [cursive's comparison page](https://github.com/gyscos/cursive/wiki/Cursive-vs-tui%E2%80%90rs).

Not to mention the work done in [cursive-markup](https://crates.io/crates/cursive-markup) :)

**Comment by jkelleyrtp** [comment]
I'd love to see someone help push this project forward! The features left for this crate are a bit "meaty" but extremely straightforward - we just need to add a few handler components/hooks and then slowly march our "subset of html" to a more semantic HTML. You might have more luck with Dioxus since we actually produce a VritualDom - and you can use that directly as your UI tree.

I'd be happy to help mentor you :)

Anyways - I chose Tui since that's what I personally know. The examples for cursive seem to be tailored around their style of UI - focusing mostly on layout and some old windows-ish theme?

The draw code in this crate for Tui is pretty simple to wrench out and either drop directly into crossterm, or maybe build a prototype of for cursive?

**Comment by saona-raimundo** [comment]
> I'd be happy to help mentor you :)

Cool! I would be happy to help out while learning more about TUIs and dioxus :) 
This would be my first collaboration like this, so please bear with me.

I will get familiar with the code in rink. But in the meantime I could leave some preliminary comments here:

- the name `rink` is already taken in crates.io
- the dependencies in this repo are still linking to paths (in your local pc?)
- if the repo is going to depend on dioxus, should they not be in the same workspace?

**Comment by jkelleyrtp** [comment]
> > I'd be happy to help mentor you :)
> 
> Cool! I would be happy to help out while learning more about TUIs and dioxus :) This would be my first collaboration like this, so please bear with me.
> 
> I will get familiar with the code in rink. But in the meantime I could leave some preliminary comments here:
> 
> * the name `rink` is already taken in crates.io
> * the dependencies in this repo are still linking to paths (in your local pc?)
> * if the repo is going to depend on dioxus, should they not be in the same workspace?

1) uhhh yep you're right :) Maybe something boring like `dioxus-tui` will be fine
2) this is now fixed! you should be able to compile and run the examples
3) rink is/was very experimental. when it gets to a stable place we can merge it into the mainline repo

Feel free to hop into the discord https://discord.gg/XgGxMSkvUM and I can answer any questions you might have as they pop up.
